baseURL = 'https://nguyencuonghut.netlify.app/'
languageCode = 'en-us'
title = 'TONY NGUYEN'
theme = 'pehtheme-hugo'
[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params] # Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.'
	mainSections = 'posts'
	author.name = 'Tony Nguyen'
	author.bio = 'Debitis assumenda esse dignissimos aperiam delectus maxime tenetur repudiandae dolore'
	author.avatar = '/images/nasa-astronaut-unsplash.jpg'
	author.twitter = 'https://twitter.com/insertapps'

[menu] # Menu management
	[[menu.main]]
		name = 'Trang chủ'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'Về tác giả'
		pageRef = '/about'
		weight = 15
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20
	[[menu.main]]
		name = 'Phân loại'
		pageRef = '/categories/'
		weight = 25

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'