baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tony Nguyen Blog'

[[menus.main]]
name = 'Trang chủ'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Bài viết'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
